- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java
- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/main/java/com/netflix/fenzo/plugins/VMLeaseObject.java
- fenzo-core/src/test/java/com/netflix/fenzo/SingleOfferModelTests.java
- fenzo-triggers/src/main/java/com/netflix/fenzo/triggers/TriggerUtils.java
Experimental support for mode where resource offers come in only once per host.
> Single resource offer mode.

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/test/java/com/netflix/fenzo/OfferRejectionsTest.java
- allow configuring max number of offers to reject per expiry interval
- unit tests for offer expiry and verifying maximum reject limit
> Offer expiry and limit configuration

- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/test/java/com/netflix/fenzo/OfferRejectionsTest.java
expire unused leases of hosts even if they are already running tasks from previous assignments
> lease expiry fix

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java
- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/test/java/com/netflix/fenzo/OfferRejectionsTest.java
scheduler builder options to enabled detailed debug info and convenience method to set to reject all expired offers
> debug info

- fenzo-core/src/main/java/com/netflix/fenzo/SchedulingResult.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/test/java/com/netflix/fenzo/ConstraintsTests.java
Handle exceptions in scheduler iteration and pass them back to the caller
> Exceptions handling

- fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/test/java/com/netflix/fenzo/AutoScalerTest.java
Allow users of AutoScaler to set delay in taking actions so intermittent short lived situations don't trigger autoscaling actions unnecessarily. 
Setting delays on autoscaler is not required.
Delays can be set separately for scaling up and scaling down actions.
New unit tests to test delays for scale up and down.
> Delay autoscale

- fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/test/java/com/netflix/fenzo/TestLotsOfTasks.java
TaskScheduler can now be shutdown to allow graceful shutdown of frameworks
> Allow shutdown

- README.md
- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java
- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/main/java/com/netflix/fenzo/AssignmentFailure.java
- fenzo-core/src/main/java/com/netflix/fenzo/PreferentialNamedConsumableResourceSet.java
- fenzo-core/src/main/java/com/netflix/fenzo/ResAllocsEvaluater.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskAssignmentResult.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskRequest.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/main/java/com/netflix/fenzo/VMResource.java
- fenzo-core/src/main/java/com/netflix/fenzo/VirtualMachineCurrentState.java
- fenzo-core/src/main/java/com/netflix/fenzo/VirtualMachineLease.java
- fenzo-core/src/main/java/com/netflix/fenzo/samples/TaskGenerator.java
- fenzo-core/src/test/java/com/netflix/fenzo/RandomTaskGenerator.java
- fenzo-core/src/test/java/com/netflix/fenzo/ResourceSetsTests.java
- fenzo-core/src/test/java/com/netflix/fenzo/TaskRequestProvider.java
- gradlew
- New two level preferential named resource set
- Resource set is created from custom attributes in mesos offers
- Support for tasks to request the new resource set
- Autoscaling and other features work with the new resource set
- New test cases for the resource set feature
> add support for new two level resource set

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/main/java/com/netflix/fenzo/VirtualMachineCurrentState.java
- fenzo-core/src/test/java/com/netflix/fenzo/BasicSchedulerTests.java
- fenzo-core/src/test/java/com/netflix/fenzo/LeaseProvider.java
Provide access to list of mesos offers being used for resource assignment for a target host (VM) so consrtaint evaluators can inspect the offers
> Provide access to list of mesos offers

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/main/java/com/netflix/fenzo/AutoScaleRules.java
- fenzo-core/src/main/java/com/netflix/fenzo/ScaleDownAction.java
- fenzo-core/src/main/java/com/netflix/fenzo/SchedulingResult.java
- fenzo-core/src/main/java/com/netflix/fenzo/ShortfallEvaluator.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskIterator.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskTracker.java
- fenzo-core/src/main/java/com/netflix/fenzo/functions/Action0.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/InternalTaskQueue.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/InvalidTierNumberException.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/QAttributes.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/QueuableTask.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/TaskQueue.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/TaskQueueException.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/TaskQueueMultiException.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/TaskQueues.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/UsageTrackedQueue.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/QueueBucket.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/SortedBuckets.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/Tier.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TierBuckets.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TieredQueue.java
- fenzo-core/src/main/java/com/netflix/fenzo/samples/SampleFramework.java
- fenzo-core/src/test/java/com/netflix/fenzo/TaskRequestProvider.java
- fenzo-core/src/test/java/com/netflix/fenzo/TaskSchedulingServiceTest.java
- fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/QueuableTaskProvider.java
- fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/SortedBucketsTest.java
- fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/TieredQueueTest.java
- Introduce task queues with possibly different implementations of the queues.
- Implement a tiered queue for multi-level scheme
- Introduce new scheduling service that wraps around the queues and calls existing TaskScheduler
- Unit tests and JavaDocs
> Task Queues

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/test/java/com/netflix/fenzo/OfferRejectionsTest.java
Issue #87 when a lease expires, reject all leases of a VM to prevent fragmentation
> Fix for Issue #87

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
Check current iteration assignment results as well for active check on VMs
> Fix active check on VMs

- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/SortedBuckets.java
handle the error case when a bucket of tiered queue is being removed and the list sort is found invalid
> Handle error in sorting inside tiered queue

- fenzo-core/src/main/java/com/netflix/fenzo/queues/TaskQueue.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/TaskQueueSla.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/QueueBucket.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/Tier.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TierSla.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TierSlas.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TieredQueue.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TieredQueueSlas.java
- fenzo-core/src/test/java/com/netflix/fenzo/LeaseProvider.java
- fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/SortedBucketsTest.java
- fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/TieredQueueTest.java
- define tier slas
- use tier slas for weighted drf across buckets of a tier
> Weighted drf across buckets of a tier

- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TierSlas.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TieredQueue.java
- change tier queue sla setting to be safe
- use copy on write internally instead of mutating sla
> safe copy on write of tiered queue sla updates

- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TierSla.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TierSlas.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TieredQueueSlas.java
- fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/TieredQueueTest.java
- Tier sla modifications are now copy-on-write 
- Additional unit tests
> Fix tier sla modifications

- fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java
- fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java
use finally to ensure clean up happens in spite of unexpected errors during pseudo scheduling
> handle any unexpected errors in pseudo scheduling

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java
- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskRequest.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
- fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java
- fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java
- fenzo-core/src/test/java/com/netflix/fenzo/ResourceSetsTests.java
- fenzo-core/src/test/java/com/netflix/fenzo/TaskSchedulingServiceTest.java
1. in TaskSchedulingService, assign resource sets before returning result
2. optimize debug logs
3. new unit tests
> assign resource sets in TaskSchedulingService results

- fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/QueuableTask.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/UsageTrackedQueue.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/QueueBucket.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/Tier.java
- fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TieredQueue.java
- fenzo-core/src/test/java/com/netflix/fenzo/TaskSchedulingServiceTest.java
- fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/QueuableTaskProvider.java
- introduce ready time for queuable tasks
- change taskSchedulingService to skip tasks that are ready only in future time
- new unit test for ensuring tasks not ready are skipped
> Task ready time

- fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java
- fenzo-core/src/test/java/com/netflix/fenzo/ShortfallAutoscalerTest.java
Fix autoscaler execution service to ensure scale up actions are invoked reliably
> fix autoscaler execute service

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java
Unsafe concurrent access to unknown lease collection in AssignableVMs class
> Fixes #167 (Unsafe concurrent access to unknown lease collection in AssignableVMs class)

- fenzo-core/src/main/java/com/netflix/fenzo/PreferentialNamedConsumableResourceSet.java
Add the ability to get usage by in PreferentialNamedConsumableResourceSet and get used count in PreferenctialNamedConsumableResource
> Minor Improvements

- fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
- fenzo-core/src/test/java/com/netflix/fenzo/ScalarResourceTests.java
Single lease mode requires resources to be negative temporarily when doing its accounting. Because scalar resources were always being reset to 0 when they were negative, this caused the creation of new resources leading to overallocation.
> fix scalar resource accounting for single lease mode
