fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/PreferentialNamedConsumableResourceSet.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskRequest.java, fenzo-core/src/main/java/com/netflix/fenzo/samples/TaskGenerator.java, fenzo-core/src/test/java/com/netflix/fenzo/RandomTaskGenerator.java, fenzo-core/src/test/java/com/netflix/fenzo/ResourceSetsTests.java, fenzo-core/src/test/java/com/netflix/fenzo/TaskRequestProvider.java
Allow tasks to specify assigned resources to track custom defined resources.
For now that includes just the named consumable resource set.
=> Allow tasks to specify assigned resources

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskRequest.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskTracker.java, fenzo-core/src/main/java/com/netflix/fenzo/VMResource.java, fenzo-core/src/main/java/com/netflix/fenzo/VirtualMachineLease.java, fenzo-core/src/main/java/com/netflix/fenzo/plugins/VMLeaseObject.java, fenzo-core/src/main/java/com/netflix/fenzo/samples/TaskGenerator.java, fenzo-core/src/test/java/com/netflix/fenzo/LeaseProvider.java, fenzo-core/src/test/java/com/netflix/fenzo/RandomTaskGenerator.java, fenzo-core/src/test/java/com/netflix/fenzo/ScalarResourceTests.java, fenzo-core/src/test/java/com/netflix/fenzo/TaskRequestProvider.java
Add support for any scalar resources to be tracked and assigned. 
The scalar resources CPU, memory, network bandwidth, and disk remain as they are currently, explicitly asked for and assigned. This new addition lets you specify any other scalar resources in a generic way, providing the scalar resource name and a value for the quantity for the resource.
This does require a change to the interfaces TaskRequest and VirtualMachineLease.
=> Scalar resources

fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java
- fix scheduling service to call internal version of getResourceStatus
- create exception at the place of throwing
=> Fix scheduling service to call internal versions of TaskScheduler

fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java, fenzo-core/src/main/java/com/netflix/fenzo/queues/InternalTaskQueue.java, fenzo-core/src/main/java/com/netflix/fenzo/samples/SampleQbasedScheduling.java, fenzo-core/src/test/java/com/netflix/fenzo/TaskSchedulingServiceTest.java
New signature now takes taskId and qAttributes instead of QueuableTask object.
=> change signature of TaskSchedulingService.removeTask

build.gradle, fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/AutoScaleRule.java, fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java, fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java, fenzo-core/src/test/java/com/netflix/fenzo/AutoScaleRuleProvider.java, fenzo-core/src/test/java/com/netflix/fenzo/AutoScalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/LeaseProvider.java, fenzo-core/src/test/java/com/netflix/fenzo/ResourceSetsTests.java
- Move to Java 8 compatibility
- Introduce minSize and maxSize as absolute limits for cluster autoscaling
- VMs are now held internally grouped by the attribute value used for cluster autoscaling
=> Autoscale chgs

fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java, fenzo-core/src/main/java/com/netflix/fenzo/ShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java, fenzo-core/src/test/java/com/netflix/fenzo/AutoScalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/OfferRejectionsTest.java
Allow optional mapping of tasks to autoscaling group names to optimize scale up trigger for shortfall based scale up
=> Optional task to autoscale group name for shortfall based scale up

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
explicitly exclude VMs that had resources assigned in the iteration when purging inactive VMs
=> Fix inactive VMs purging

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/plugins/VMLeaseObject.java
The underlying attribute map for a VM may change over time. Without this isolation concurrency issue may happen.
=> Use immutable VM attribute collection in VirtualMachineLease implemnetations

fenzo-core/src/test/java/com/netflix/fenzo/TaskSchedulingServiceTest.java
allow additional time to get results back from scheduling service in unit test
=> unit test fix

build.gradle
Hi all,
After I'd checked out this repo I tried a `gradle build` which finally failed with this error message:
```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/patrick/git/Fenzo-Fork/build.gradle' line: 27
* What went wrong:
A problem occurred evaluating root project 'fenzo'.
> org/gradle/api/internal/project/AbstractProject
```
Running `gradle build --stacktrace` offered a more precise hint on the root cause:
```
java.lang.ClassNotFoundException: org.gradle.api.internal.project.AbstractProject
```
* __OS:__ Ubuntu 16.04
* __JDK:__ OpenJDK version 1.8.0_121
* __Gradle version:__ 3.4.1 (Revision: 9eb76efdd3d034dc506c719dac2955efb5ff9a93)
I started with bringing the version of `com.netflix.nebula:gradle-netflixoss-project-plugin` up to 3.5.2  (see …
=> Build broken under Gradle 3.4.1 

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java, fenzo-core/src/main/java/com/netflix/fenzo/BaseShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/InternalVMCloner.java, fenzo-core/src/main/java/com/netflix/fenzo/NaiveShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/OptimizingShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskTracker.java, fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java, fenzo-core/src/main/java/com/netflix/fenzo/queues/InternalTaskQueues.java, fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/QueueBucket.java, fenzo-core/src/main/java/com/netflix/fenzo/queues/tiered/TieredQueue.java, fenzo-core/src/test/java/com/netflix/fenzo/AutoScalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/NaiveShortfallEvaluatorTest.java, fenzo-core/src/test/java/com/netflix/fenzo/ShortfallAutoscalerTest.java
New optimal resource shortfall analyzer that can be optionally chosen when building scheduling service.
This works with existing task constraints, fitness functions, and autoscale rules to determine the right number of VMs to add for each autoscale group to satisfy the resource demands from tasks that failed assignments in the recent scheduling iteration.
=> new optimal shortfall analyzer

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/BaseShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/InternalVMCloner.java, fenzo-core/src/main/java/com/netflix/fenzo/NaiveShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/OptimizingShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/ShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java, fenzo-core/src/test/java/com/netflix/fenzo/AutoScalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/OfferRejectionsTest.java, fenzo-core/src/test/java/com/netflix/fenzo/ShortfallAutoscalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/VMCollectionTest.java
- Fix calculation of number of pseudo VMs to add
- Make full copy of lease when cloning for pseudo VMs
- Don't call reject action on pseudo VM leases
- new unit tests
=> Don't call lease reject action on pseudo VMs

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java, fenzo-core/src/test/java/com/netflix/fenzo/ShortfallAutoscalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/VMCollectionTest.java
1. check if lease is rejectable before calling reject action. 
2. filter out leases from inactive VMs before cloning
=> fix VM cloning for pseudo scheduling

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java, fenzo-core/src/main/java/com/netflix/fenzo/AutoScalerInput.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
The scale down constraint evaluators work with the merged active/inactive lists,
but we need to do extra processing in AutoScaler to enforce min/max idle constraint
for the active server groups.
=> Handle idle/inactive VMs directly in AutoScaler

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java, fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java, fenzo-core/src/test/java/com/netflix/fenzo/ShortfallAutoscalerTest.java
- Fix cloning of leases for pseudo VMs, update totals before use
- unit test to replicate problem with cloned leases before this fix when using active VMs list
=> Fix pseudo VMs lease cloning

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java
expire any unknown lease Ids after adding new leases when preparing VMs for scheduling
=> Change order of releasing leases

fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java
I can't figure out why this was commented out. Was this intentional? 
It causes scheduling with fenzo to non-deterministic with a large number of hosts which makes simulating a framework that uses fenzo difficult.
=> Use hostname as a tie break when fitness is equal

fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java
Sharing the same timestamp between the inactive and active server groups,
introduces undesired scale-time dependencies between the two.
=> Handle inactive agent termination cycle independently from the active one

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVMs.java, fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java, fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java, fenzo-core/src/main/java/com/netflix/fenzo/InternalVMCloner.java, fenzo-core/src/main/java/com/netflix/fenzo/OptimizingShortfallEvaluator.java, fenzo-core/src/main/java/com/netflix/fenzo/StateMonitor.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java, fenzo-core/src/main/java/com/netflix/fenzo/TaskSchedulingService.java, fenzo-core/src/main/java/com/netflix/fenzo/VMCollection.java, fenzo-core/src/main/java/com/netflix/fenzo/samples/SampleQbasedScheduling.java, fenzo-core/src/test/java/com/netflix/fenzo/AutoScalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/ShortfallAutoscalerTest.java, fenzo-core/src/test/java/com/netflix/fenzo/TaskSchedulingServiceTest.java, fenzo-core/src/test/java/com/netflix/fenzo/queues/tiered/TieredQueueTest.java
- change autoscaler to be synchronously executed as part of the scheduling iteration while keeping the callback execution on a separate thread
- change shortfall analysis implementation to be synchronously executed as part of the autoscaler
- add withAutoscaleDisabledVmDurationInSecs for users that want to disable VMs for a fixed duration that is different from the cooldown value
=> Execute autoscaler synchronously on scheduler thread

fenzo-core/src/main/java/com/netflix/fenzo/AutoScaler.java
Remove the info log lines for autoscaling
Add debug logs for the autoscaler processing and executing of callbacks
=> Cleanup autoscaler log statements

fenzo-core/src/main/java/com/netflix/fenzo/AssignableVirtualMachine.java
Make AssignableVirtualMachine public so that it can be used in `TaskScheduler.withAssignableVMsEvaluator`.
=> make AssignableVirtualMachine public

build.gradle
Hi folks,
As you might be aware, JFrog is sunsetting Bintray and JCenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
This is to use maven central instead of jcenter
=> Remove usages of jcenter()
